#!/usr/bin/env node
/**
 * Snapshot Maia's JSONL logs out of the backend container into typed fixtures.
 *
 * Investigate reads its records through a port, and the seed adapter behind
 * that port is fed from here. The records are the real ones — the container's
 * own lines, unedited — so the surface is built against the shapes the backend
 * actually writes rather than against a guess at them. Re-run it whenever the
 * log schema moves:
 *
 *   node scripts/snapshot-logs.mjs
 *
 * The synthesized records that cover states your traffic has not reached yet
 * live beside the output in `synthesized_records.ts` and are written by hand,
 * never by this script. Nothing here runs at build time or in the app.
 */

import { execFileSync } from 'node:child_process'
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const HERE = dirname(fileURLToPath(import.meta.url))
const OUT_DIR = resolve(HERE, '../src/infrastructure/observability/fixtures')
const OUT_FILE = resolve(OUT_DIR, 'snapshot_records.ts')

const CONTAINER = process.env.HARNESS_BACKEND_CONTAINER ?? 'harness-backend'
const LOG_DIR = process.env.HARNESS_LOG_DIR ?? '/home/appuser/.logs'

const STREAMS = [
  {
    file: 'agent-context.jsonl',
    constant: 'MODEL_CONTEXT_SNAPSHOT',
    type: 'ModelContextEvent',
  },
  {
    file: 'response-gate.jsonl',
    constant: 'RESPONSE_GATE_SNAPSHOT',
    type: 'ResponseGateEvent',
  },
]

function readStream(file) {
  const raw = execFileSync(
    'docker',
    ['exec', CONTAINER, 'cat', `${LOG_DIR}/${file}`],
    { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
  )

  return raw
    .split('\n')
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line, index) => {
      try {
        return JSON.parse(line)
      } catch (error) {
        throw new Error(`${file} line ${index + 1} is not JSON: ${error.message}`)
      }
    })
}

function main() {
  const captured = STREAMS.map((stream) => ({
    ...stream,
    records: readStream(stream.file),
  }))

  const body = captured
    .map(
      (stream) =>
        `export const ${stream.constant}: ${stream.type}[] = ${JSON.stringify(
          stream.records,
          null,
          2,
        )}\n`,
    )
    .join('\n')

  const header = `/* Generated by scripts/snapshot-logs.mjs — do not edit by hand.
 *
 * Real records read out of ${CONTAINER}:${LOG_DIR}. Captured ${new Date().toISOString()}.
 * Re-run the script to refresh; hand-written coverage lives in
 * synthesized_records.ts. */

import type { ModelContextEvent, ResponseGateEvent } from '../../../application/observability/schemas'

`

  mkdirSync(OUT_DIR, { recursive: true })
  writeFileSync(OUT_FILE, `${header}${body}`, 'utf8')

  for (const stream of captured) {
    console.log(`${stream.file}: ${stream.records.length} records`)
  }
  console.log(`wrote ${OUT_FILE}`)
}

main()
